name: Limbo
version: '1.0-SNAPSHOT'
main: network.warzone.limbo.LimboPlugin
api-version: '1.21.8'
#commands:
#  refetch:
#    description: Refetches the player's data
#    usage: /refetch
#    permission: limbo.refetch
